#!/usr/bin/env python
import sys
import norm
import argparse
import subprocess
import os.path as path
import signal

ROOT_PATH = path.normpath(path.join(__file__, '..'))


def signal_handler(sig, frame):
    print('So long')
    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)


def run_monitor(args):
    subprocess.run(
        [path.join(ROOT_PATH, 'monitor/target/release/monitor'), *args])


def run_norm(args):
    sysadmin.norm.run(args)


commands = {
    'norm': run_norm,
    'monitor': run_monitor
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('command', choices=commands.keys())
    parser.add_argument('args', nargs='*')
    args = parser.parse_args()
    commands[args.command](list(args.args))
