#!/usr/bin/env python
import sys
import sysadmin.norm
import argparse

commands = {
    'norm': sysadmin.norm.run
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('command', choices=commands.keys())
    parser.add_argument('args', nargs='*')
    args = parser.parse_args()
    commands[args.command](list(args.args))
